import React, { Suspense } from "react";
import Loading from "../loading";
import AppoitmentHistory from "@/components/DoctorAccount/AppoitmentHistory";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Appoitment History | Doctor",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <Suspense fallback={<Loading />}>
      <AppoitmentHistory />
    </Suspense>
  );
};

export default page;
