import React, { Suspense } from "react";
import Loading from "../loading";
import MyAppoitments from "@/components/DoctorAccount/MyAppoitments";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Upcomming Appoitment | Doctor",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <Suspense fallback={<Loading />}>
      <MyAppoitments />
    </Suspense>
  );
};

export default page;
