import React, { Suspense } from "react";
import Loading from "./loading";
import DoctorProfile from "@/components/DoctorAccount/DoctorProfile";

import { Metadata } from "next";
export const metadata: Metadata = {
  title: "My Account",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <Suspense fallback={<Loading />}>
      <DoctorProfile />
    </Suspense>
  );
};

export default page;
