import Navbar from "@/components/Navbar/Navbar";
import { Metadata } from "next";
import React, { Suspense } from "react";
import Loading from "./loading";
import Footer from "@/components/Footer/Footer";
export const metadata: Metadata = {
  title: "Checkout ",
  description: "Generated by create next app",
};
const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <Suspense fallback={<Loading />}>
      <Navbar />
      {children}
      <Footer />
    </Suspense>
  );
};

export default layout;
