import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import type { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";
export const metadata: Metadata = {
  title: "Clinicall - log in or sign up",
  description: "Generated by create next app",
};

export default function labTestlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Suspense fallback={<Loading />}>
        <Footer />
      </Suspense>
    </>
  );
}
