import type { Metadata } from "next";
import { Suspense } from "react";
import NavBar from "@/components/Microsite/NavBar";
import Loading from "./Home/loading";
import Footer from "@/components/Microsite/Footer";
export const metadata: Metadata = {
  title: "Bkash Campaign",
  description: "Generated by create next app",
};

export default function labTestlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loading />}>
      {" "}
      <NavBar />
      {children}
      <Footer />
    </Suspense>
  );
}
