
import type { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";
import NavBar from "@/components/Microsite/NavBar";
import Footer from "@/components/Microsite/Footer";
export const metadata: Metadata = {
  title: "Invoice Page",
  description: "Generated by create next app",
};

export default function labTestlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loading />}>
      {/* <NavBar /> */}
      {children}
      {/* <Footer /> */}
    </Suspense>
  );
}
